### ISSUE TITLE
Error in jstart

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#595]
FreeBSD version ( uname -a ): FreeBSD 13.0-RELEASE

CBSD version ( cbsd version ): 13.0.6

Only partial list of jails is chown in `cbsd jstart` menu:
```
njails-6# cbsd jstart
List of offline jail
/usr/local/cbsd/sudoexec/jstart: arithmetic expression: variable conversion error: " curr_time - state_time "
 0 .. CANCEL
 a .. bderp6 on local

njails-6# cbsd jls
JNAME       JID  IP4_ADDR         HOST_HOSTNAME               PATH                          STATUS
bderp6      0    10.192.6.134/24  bderp6.ldlccloud.local      /jails/cbsd/jails/bderp6      Off
consuldev3  1    10.192.6.131/24  consuldev3.ldlccloud.local  /jails/cbsd/jails/consuldev3  On
gle6        0    10.192.6.133/24  gle6.ldlccloud.local        /jails/cbsd/jails/gle6        Off
jailnet1    0    10.192.6.130/24  jailnet1.ldlccloud.local    /jails/cbsd/jails/jailnet1    Off
```

**Comment by olevole** [comment]
fixed: https://github.com/cbsd/cbsd/commit/cbb247fec67b1b20cf7195bc2e34f89633825ffe

@Peter2121  I will send the update to the ports immediately, thanks!

**Comment by Peter2121** [comment]
I've mentioned the problem in jstart, but your commit modifies jstop.
So, the same error is still present in the new version:

```
njails-6# cbsd version
13.0.7
njails-6# cbsd jstart
List of offline jail
/usr/local/cbsd/sudoexec/jstart: arithmetic expression: variable conversion error: " curr_time - state_time "
 0 .. CANCEL
 a .. jailnet1 on local
```

**Comment by olevole** [comment]
Try to start + stop container. This should fix it, because **jstop** is update the value in state_time column. 

With the previous version you should have '(strftime('%s','now'))' instead of timestamp, check this:

```
sqlite3 ~cbsd/var/db/local.sqlite "select jname,state_time from jails;"
```
